### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by nabijaczleweli** [milleniumbug/seed11#2]

**Comment by milleniumbug** [comment]
I can take obvious way, and adopt semver, make a stable release, and declare all stuff before as version 0. This requires two additional things to do: a.) document the API (partially done) b.) considering what constitutes a breaking change for a C++ API (adding an overload can break API, adding default function parameter breaks API because people can make function pointers, and so on, and so on). This gave me a project idea BTW :D

**Comment by milleniumbug** [comment]
Documented the public API, adopted semver. Non-documented API is experimental, but probably won't change much. Made a breaking change before making first release. All is well.
